# Generated by Django 4.0 on 2022-03-17 14:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_post', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('body', models.CharField(blank=True, max_length=255)),
                ('pic', models.ImageField(upload_to='publish')),
                ('user_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sharing_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_post', models.DateTimeField(default=django.utils.timezone.now)),
                ('the_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SharingPost', to='publish.post')),
                ('the_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SharingPost', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='report_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Why_reported', models.CharField(max_length=255)),
                ('time_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReportPost', to='publish.post')),
                ('who_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Whoreport', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='publish.post')),
                ('user_like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('time_comment', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='publish.post')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='auth.user')),
            ],
            options={
                'ordering': ('-time_comment',),
            },
        ),
    ]
